name: Deploy DotNet project to Azure Function App

on:
  push:
    branches:
        - master

env:
  AZURE_FUNCTIONAPP_NAME: 'linkShorter'   
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'     
  DOTNET_VERSION: '8.0'                   

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Restore Dependencies'
      run: dotnet restore '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'

    - name: 'Build Project'
      run: dotnet build --configuration Release --output ./output

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}